### ISSUE TITLE
some clone of your reposetup…

### ISSUE THREAD

**Issue by Sylvain303** [agateau/reposetup#1]
Hi,

Thanks for your code.

Based on what you've done, I produced some command line git repository manager too.

I don't have reproduced the remote repository behavior you are describing, as I only use bare repository for my local workstations copying modifying stuff, and pushing changes via local SSH.

Just to let you know and sharing : https://github.com/Sylvain303/mygit_manager

Best regards.

**Comment by agateau** [comment]
Nice! Thanks for letting me know.
